name: dsh_remote
description: Flutter app to remotely control local DeepSeek Harness (DSH) through a bridge.
publish_to: 'none'
version: 0.3.2+4

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  web_socket_channel: ^2.4.0
  cupertino_icons: ^1.0.6
  flutter_secure_storage: ^9.2.4
  flutter_zxing: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/dsh_logo.png
